const PLACES = [
  {
    name: "Algarve",
    location: "Portugal",
    long: -7.93044,
    lat: 37.019356,
    img: "assets/images/popular-destinations/algarve.jpg",
    type: "beach",
  },
  {
    name: "Atlanta",
    location: "Georgia",
    long: -84.38633,
    lat: 33.753746,
    img: "assets/images/popular-destinations/atlanta.jpg",
    type: "city",
  },
  {
    name: "Bali",
    location: "Indonesia",
    long: 115.188919,
    lat: -8.409518,
    img: "assets/images/popular-destinations/bali.jpg",
    type: "beach",
  },
  {
    name: "Bass Lake",
    location: "California",
    long: -119.5664,
    lat: 37.3247,
    img: "assets/images/popular-destinations/bass-lake.jpg",
    type: "mountains",
  },
  {
    name: "Big Sky",
    location: "Montana",
    long: -111.25312,
    lat: 45.26599,
    img: "assets/images/popular-destinations/big-sky.jpg",
    type: "mountains",
  },
  {
    name: "Delray Beach",
    location: "Florida",
    long: -80.105545,
    lat: 26.459763,
    img: "assets/images/popular-destinations/delray-beach.jpg",
    type: "beach",
  },
  {
    name: "Marco Island",
    location: "Florida",
    long: -81.714722,
    lat: 25.940556,
    img: "assets/images/popular-destinations/marco-island.jpg",
    type: "beach",
  },
  {
    name: "Nashville",
    location: "Tennessee",
    long: -86.76796,
    lat: 36.174465,
    img: "assets/images/popular-destinations/nashville.jpg",
    type: "city",
  },
  {
    name: "Algarve",
    location: "Portugal",
    long: -7.93044,
    lat: 37.019356,
    img: "assets/images/popular-destinations/algarve.jpg",
    type: "beach",
  },
  {
    name: "Atlanta",
    location: "Georgia",
    long: -84.38633,
    lat: 33.753746,
    img: "assets/images/popular-destinations/atlanta.jpg",
    type: "city",
  },
  {
    name: "Bali",
    location: "Indonesia",
    long: 115.188919,
    lat: -8.409518,
    img: "assets/images/popular-destinations/bali.jpg",
    type: "beach",
  },
  {
    name: "Bass Lake",
    location: "California",
    long: -119.5664,
    lat: 37.3247,
    img: "assets/images/popular-destinations/bass-lake.jpg",
    type: "mountains",
  },
  {
    name: "Big Sky",
    location: "Montana",
    long: -111.25312,
    lat: 45.26599,
    img: "assets/images/popular-destinations/big-sky.jpg",
    type: "mountains",
  },
  {
    name: "Delray Beach",
    location: "Florida",
    long: -80.105545,
    lat: 26.459763,
    img: "assets/images/popular-destinations/delray-beach.jpg",
    type: "beach",
  },
  {
    name: "Marco Island",
    location: "Florida",
    long: -81.714722,
    lat: 25.940556,
    img: "assets/images/popular-destinations/marco-island.jpg",
    type: "beach",
  },
  {
    name: "Nashville",
    location: "Tennessee",
    long: -86.76796,
    lat: 36.174465,
    img: "assets/images/popular-destinations/nashville.jpg",
    type: "city",
  },
  {
    name: "Algarve",
    location: "Portugal",
    long: -7.93044,
    lat: 37.019356,
    img: "assets/images/popular-destinations/algarve.jpg",
    type: "beach",
  },
  {
    name: "Atlanta",
    location: "Georgia",
    long: -84.38633,
    lat: 33.753746,
    img: "assets/images/popular-destinations/atlanta.jpg",
    type: "city",
  },
  {
    name: "Bali",
    location: "Indonesia",
    long: 115.188919,
    lat: -8.409518,
    img: "assets/images/popular-destinations/bali.jpg",
    type: "beach",
  },
  {
    name: "Bass Lake",
    location: "California",
    long: -119.5664,
    lat: 37.3247,
    img: "assets/images/popular-destinations/bass-lake.jpg",
    type: "mountains",
  },
  {
    name: "Big Sky",
    location: "Montana",
    long: -111.25312,
    lat: 45.26599,
    img: "assets/images/popular-destinations/big-sky.jpg",
    type: "mountains",
  },
  {
    name: "Delray Beach",
    location: "Florida",
    long: -80.105545,
    lat: 26.459763,
    img: "assets/images/popular-destinations/delray-beach.jpg",
    type: "beach",
  },
  {
    name: "Marco Island",
    location: "Florida",
    long: -81.714722,
    lat: 25.940556,
    img: "assets/images/popular-destinations/marco-island.jpg",
    type: "beach",
  },
  {
    name: "Nashville",
    location: "Tennessee",
    long: -86.76796,
    lat: 36.174465,
    img: "assets/images/popular-destinations/nashville.jpg",
    type: "city",
  },
];
